import type { Trek } from '@/types'

export const MOCK_TREKS: Trek[] = [
  {
    id: '1',
    slug: 'everest-base-camp',
    name: 'Everest Base Camp',
    region: 'Khumbu',
    difficulty: 'Challenging',
    duration: 14,
    maxAltitude: 5364,
    distance: 130,
    price: 1850,
    rating: 4.9,
    reviewCount: 2847,
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80',
      'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=1200&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    ],
    highlights: ['Khumbu Icefall views', 'Namche Bazaar', 'Tengboche Monastery', 'Kala Patthar sunrise'],
    description: 'The iconic journey to the foot of the world\'s highest peak. Walk in the footsteps of legends through Sherpa villages, ancient monasteries, and breathtaking glacial landscapes.',
    aiSummary: 'Perfect for experienced hikers seeking the ultimate Himalayan adventure. Best completed Oct–Nov or Mar–May. Acclimatization is critical — the itinerary includes two rest days.',
    startPoint: 'Lukla',
    endPoint: 'Lukla',
    bestSeason: ['March', 'April', 'May', 'October', 'November'],
    groupSize: { min: 1, max: 12 },
    includes: ['All permits', 'Experienced guide', 'Porter (1:2 ratio)', 'Tea house accommodation', 'All meals on trail', 'Airport transfers'],
    excludes: ['International flights', 'Travel insurance', 'Personal gear', 'Tips', 'Alcoholic beverages'],
    itinerary: [
      { day: 1, title: 'Fly Kathmandu → Lukla, Trek to Phakding', description: 'Scenic 35-minute flight to Lukla airstrip, then a gradual downhill trek along the Dudh Koshi river.', altitude: 2610, distance: 8, accommodation: 'Tea house' },
      { day: 2, title: 'Phakding → Namche Bazaar', description: 'Cross suspension bridges adorned with prayer flags and ascend steeply to the Sherpa capital.', altitude: 3440, distance: 11, accommodation: 'Guesthouse' },
      { day: 3, title: 'Acclimatization Day — Namche', description: 'Rest day with optional hike to Everest View Hotel for first glimpse of the summit.', altitude: 3440, distance: 5, accommodation: 'Guesthouse' },
      { day: 4, title: 'Namche → Tengboche', description: 'Through rhododendron forests to the spiritual heart of the Khumbu valley.', altitude: 3867, distance: 10, accommodation: 'Monastery guesthouse' },
      { day: 5, title: 'Tengboche → Dingboche', description: 'Alpine meadows and views of Ama Dablam lead to the upper Khumbu.', altitude: 4410, distance: 11, accommodation: 'Tea house' },
      { day: 6, title: 'Acclimatization Day — Dingboche', description: 'Hike to Nangkartshang peak (5083m) for panoramic views.', altitude: 4410, distance: 6, accommodation: 'Tea house' },
      { day: 7, title: 'Dingboche → Lobuche', description: 'Cross the lateral moraine of the Khumbu glacier past memorials to fallen climbers.', altitude: 4940, distance: 10, accommodation: 'Tea house' },
      { day: 8, title: 'Lobuche → Gorak Shep → EBC', description: 'The final push. Reach Everest Base Camp (5364m) and absorb the magnitude of Chomolungma.', altitude: 5364, distance: 14, accommodation: 'Tea house at Gorak Shep' },
      { day: 9, title: 'Kala Patthar Sunrise → Pheriche', description: 'Pre-dawn summit of Kala Patthar (5545m) for the most celebrated Everest view on earth.', altitude: 4280, distance: 15, accommodation: 'Tea house' },
    ],
    availableDates: ['2024-10-01', '2024-10-15', '2024-11-01', '2024-11-15', '2025-03-15', '2025-04-01'],
    coordinates: { lat: 27.9881, lng: 86.9250 },
    elevation: [
      { day: 1, altitude: 2610, location: 'Phakding' },
      { day: 2, altitude: 3440, location: 'Namche' },
      { day: 3, altitude: 3440, location: 'Namche' },
      { day: 4, altitude: 3867, location: 'Tengboche' },
      { day: 5, altitude: 4410, location: 'Dingboche' },
      { day: 6, altitude: 4410, location: 'Dingboche' },
      { day: 7, altitude: 4940, location: 'Lobuche' },
      { day: 8, altitude: 5364, location: 'Base Camp' },
      { day: 9, altitude: 5545, location: 'Kala Patthar' },
    ],
  },
  {
    id: '2',
    slug: 'annapurna-circuit',
    name: 'Annapurna Circuit',
    region: 'Annapurna',
    difficulty: 'Moderate',
    duration: 18,
    maxAltitude: 5416,
    distance: 230,
    price: 1650,
    rating: 4.8,
    reviewCount: 1923,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
      'https://images.unsplash.com/photo-1605543667606-52b0bf0b402c?w=1200&q=80',
    ],
    highlights: ['Thorong La Pass', 'Muktinath Temple', 'Manang Valley', 'Poon Hill sunset'],
    description: 'The world\'s greatest circuit trek — a 230km journey traversing the entire Annapurna massif, crossing the legendary Thorong La Pass at 5416m.',
    aiSummary: 'Ideal for trekkers who want cultural depth and dramatic elevation change. The circuit crosses 6 ecological zones and passes through both Hindu and Buddhist areas.',
    startPoint: 'Besisahar',
    endPoint: 'Nayapul',
    bestSeason: ['October', 'November', 'March', 'April'],
    groupSize: { min: 1, max: 16 },
    includes: ['TIMS & ACAP permits', 'Guide & porter', 'All accommodation', 'All meals', 'Ground transport'],
    excludes: ['Flights', 'Insurance', 'Personal expenses', 'Tips'],
    itinerary: [],
    availableDates: ['2024-10-05', '2024-10-20', '2024-11-05'],
    coordinates: { lat: 28.5971, lng: 84.1167 },
    elevation: [],
  },
  {
    id: '3',
    slug: 'langtang-valley',
    name: 'Langtang Valley',
    region: 'Langtang',
    difficulty: 'Moderate',
    duration: 10,
    maxAltitude: 4984,
    distance: 75,
    price: 890,
    rating: 4.7,
    reviewCount: 891,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80'],
    highlights: ['Kyanjin Gompa', 'Langtang Glacier', 'Yak cheese farms', 'Tserko Ri views'],
    description: 'The "valley of glaciers" — a stunning yet crowd-free alternative to Everest, just 3 hours from Kathmandu. Tibetan culture, yaks, and dramatic peaks await.',
    aiSummary: 'Perfect first Himalayan trek. Shorter approach from Kathmandu makes this excellent value. Strong cultural experience with Tamang and Tibetan communities.',
    startPoint: 'Syabrubesi',
    endPoint: 'Syabrubesi',
    bestSeason: ['March', 'April', 'May', 'October', 'November', 'December'],
    groupSize: { min: 1, max: 12 },
    includes: ['All permits', 'Guide & porter', 'Accommodation', 'Meals', 'Transport'],
    excludes: ['Flights', 'Insurance', 'Tips'],
    itinerary: [],
    availableDates: ['2024-10-01', '2024-10-15', '2024-11-01', '2024-12-01'],
    coordinates: { lat: 28.2130, lng: 85.5161 },
    elevation: [],
  },
  {
    id: '4',
    slug: 'manaslu-circuit',
    name: 'Manaslu Circuit',
    region: 'Manaslu',
    difficulty: 'Challenging',
    duration: 16,
    maxAltitude: 5160,
    distance: 177,
    price: 2200,
    rating: 4.9,
    reviewCount: 432,
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&q=80'],
    highlights: ['Larkya La Pass', 'Remote Tibetan villages', 'World\'s 8th highest peak', 'Birendra Lake'],
    description: 'Nepal\'s last great wilderness trek. The restricted-area permit keeps crowds minimal on this raw, remote circuit around the world\'s 8th highest mountain.',
    aiSummary: 'For experienced trekkers seeking solitude. Restricted-area permits are mandatory and expensive but worth every dollar — this feels like the Annapurna Circuit did 30 years ago.',
    startPoint: 'Soti Khola',
    endPoint: 'Dharapani',
    bestSeason: ['September', 'October', 'November', 'March', 'April'],
    groupSize: { min: 2, max: 10 },
    includes: ['Restricted area permit', 'TIMS', 'Guide & porter', 'All meals & accommodation'],
    excludes: ['Flights to Kathmandu', 'Insurance', 'Tips', 'Personal gear'],
    itinerary: [],
    availableDates: ['2024-10-08', '2024-11-03'],
    coordinates: { lat: 28.5500, lng: 84.5600 },
    elevation: [],
  },
  {
    id: '5',
    slug: 'upper-mustang',
    name: 'Upper Mustang',
    region: 'Mustang',
    difficulty: 'Moderate',
    duration: 12,
    maxAltitude: 3840,
    distance: 150,
    price: 3100,
    rating: 4.8,
    reviewCount: 287,
    image: 'https://images.unsplash.com/photo-1571306977140-b5aa64b2e19b?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1571306977140-b5aa64b2e19b?w=1200&q=80'],
    highlights: ['Lo Manthang walled city', 'Ancient cave monasteries', 'Martian landscape', 'Tibetan culture'],
    description: 'The forbidden kingdom — a surreal lunar landscape where ancient Tibetan civilization has survived unchanged for centuries. Only 1,000 permits issued per year.',
    aiSummary: 'Lower altitude than most Nepal treks but maximum cultural and visual impact. The restricted permit ($500/10 days) is the highest cost but this is a bucket-list destination unlike any other.',
    startPoint: 'Jomsom',
    endPoint: 'Jomsom',
    bestSeason: ['May', 'June', 'July', 'August', 'September'],
    groupSize: { min: 1, max: 8 },
    includes: ['RAP permit', 'Liaison officer', 'Guide & porter', 'All meals & accommodation', 'Flight Pokhara-Jomsom'],
    excludes: ['International flights', 'Insurance', 'Tips', 'Personal items'],
    itinerary: [],
    availableDates: ['2024-10-02', '2024-10-16', '2025-05-05', '2025-06-01'],
    coordinates: { lat: 29.1816, lng: 83.9694 },
    elevation: [],
  },
  {
    id: '6',
    slug: 'gokyo-lakes',
    name: 'Gokyo Lakes & Ri',
    region: 'Khumbu',
    difficulty: 'Moderate',
    duration: 12,
    maxAltitude: 5360,
    distance: 110,
    price: 1550,
    rating: 4.85,
    reviewCount: 1104,
    image: 'https://images.unsplash.com/photo-1562329265-95a6d7a83440?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1562329265-95a6d7a83440?w=1200&q=80'],
    highlights: ['Gokyo Ri panorama', 'Five sacred lakes', 'Ngozumpa Glacier', 'Renjo La Pass'],
    description: 'The most beautiful alternative to EBC — turquoise sacred lakes reflecting Everest, Lhotse, Makalu and Cho Oyu in a single breathtaking 360° view from Gokyo Ri.',
    aiSummary: 'Often ranked higher in satisfaction than EBC by returning trekkers. Less crowded, more visually spectacular, and the lakes add a magical quality unique in the Himalaya.',
    startPoint: 'Lukla',
    endPoint: 'Lukla',
    bestSeason: ['October', 'November', 'March', 'April', 'May'],
    groupSize: { min: 1, max: 12 },
    includes: ['All permits', 'Guide & porter', 'Tea house accommodation', 'All meals', 'Airport transfers'],
    excludes: ['Flights', 'Insurance', 'Personal gear', 'Tips'],
    itinerary: [],
    availableDates: ['2024-10-10', '2024-10-25', '2024-11-10'],
    coordinates: { lat: 27.9600, lng: 86.6700 },
    elevation: [],
  },
]

export const REGIONS = ['Khumbu', 'Annapurna', 'Langtang', 'Manaslu', 'Mustang', 'Dolpo', 'Kanchenjunga']
export const DIFFICULTIES = ['Easy', 'Moderate', 'Challenging', 'Extreme']
